env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  jest/globals: true
plugins:
  - jest
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  semi: off
  arrow-parens: warn
  no-undef: warn
